import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from './Components/Header/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
    
      <body >
        <div className='bg-purple-400'>
       
        <Header />
        <div className='bg-white p-6'>
          {children}
        </div>
      
        </div>
       
        </body>
    </html>
  )
}
