import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from './Components/Header/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
    
      <body >
        <div className='bg-purple-100 py-12'>

      
        <div className=' w-9/12 items-center bg-white py-6 mx-auto'>
       
        <Header />
        <div className='bg-white p-6 w-11/12 flex flex-col items-center justify-center mx-auto'>
          {children}
        </div>
      
        </div>
        </div>
        </body>
    </html>
  )
}
